'use client';
import Toast from "@/components/ui/Toast";
import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Gujarati, Rozha_One } from "next/font/google";
const rozhaOne = Rozha_One({
  variable: "--font-rozha",
  weight: "400",
  subsets: ["latin"],
});
const notoSerifGujarati = Noto_Serif_Gujarati({
  variable: "--font-noto-gujarati",
  weight: ["600", "700"],
  subsets: ["gujarati"],
});

import "./globals.css";
import { ToastContext } from "@/app/context/ToastContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ❌ REMOVE metadata export (not allowed in client component)
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // GLOBAL TOAST SYSTEM
 // add state in layout
  const [message, setMessage] = useState("");
  const [type, setType] = useState<"success" | "error" | "info" | "">("");
//create global function
  const showMessage = (
    msgType: "success" | "error" | "info",
    text: string
  ) => {
    setMessage(text);
    setType(msgType);

    setTimeout(() => {
      setMessage("");
      setType("");
    }, 3000);
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSerifGujarati.variable} ${rozhaOne.variable} antialiased`}>
         {/*making it global */}
        <ToastContext.Provider value={{ showMessage }}>
          {children}
        </ToastContext.Provider>

        {/* ✅ TOAST UI */}
        <Toast message={message} type={type} />

      </body>
    </html>
  );
}