'use client';

import { useState } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContext } from "@/app/context/ToastContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ❌ REMOVE metadata export (not allowed in client component)
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // GLOBAL TOAST SYSTEM
 // add state in layout
  const [message, setMessage] = useState("");
  const [type, setType] = useState<"success" | "error" | "info" | "">("");
//create global function
  const showMessage = (
    msgType: "success" | "error" | "info",
    text: string
  ) => {
    setMessage(text);
    setType(msgType);

    setTimeout(() => {
      setMessage("");
      setType("");
    }, 3000);
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         {/*making it global */}
        <ToastContext.Provider value={{ showMessage }}>
          {children}
        </ToastContext.Provider>

        {/* ✅ TOAST UI */}
        {message && (
          <div
            style={{
              position: "fixed",
              top: 20,
              right: 20,
              zIndex: 9999,
              padding: "12px 18px",
              borderRadius: "10px",
              color: "white",
              fontSize: "14px",
              fontWeight: 500,
              background:
                type === "success"
                  ? "#16a34a"
                  : type === "error"
                  ? "#dc2626"
                  : "#2563eb",
              boxShadow: "0 8px 20px rgba(0,0,0,0.2)",
            }}
          >
            {message}
          </div>
        )}

      </body>
    </html>
  );
}